name: Publish base splork image

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --tag splorkci -f Dockerfile.ci

      - name: Build base splork image
        run: docker run --rm -v ./build:/app/build splorkci

      - uses: actions/upload-artifact@v3
        with:
          name: splork.bin
          path: build/splork.bin

      - uses: actions/upload-artifact@v3
        with:
          name: splork.uf2
          path: build/splork.uf2

      - uses: actions/upload-artifact@v3
        with:
          name: splork_offset.json
          path: build/splork_offset.json

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            - build/splork.uf2
            - build/splork.bin
            - build/splork_offset.json
